version: "1.0"
services:
  server:
    build:
      context: .
    ports:
      - 8888:8888
    volumes:
      - ./model:/model
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
